#!/usr/bin/env python3
"""
Interactive .env file setup script for Overseer Bot UI.

This script helps users create or update their .env file with proper configuration.
It prompts for required values and can generate secure credentials.

Usage:
    python setup_env.py          # Interactive mode
    python setup_env.py --help   # Show help
"""

import os
import sys
import secrets
import base64
import getpass
from pathlib import Path


def print_header(text):
    """Print a formatted header."""
    print("\n" + "=" * 70)
    print(f"  {text}")
    print("=" * 70)


def print_info(text):
    """Print an info message."""
    print(f"ℹ️  {text}")


def print_success(text):
    """Print a success message."""
    print(f"✅ {text}")


def print_warning(text):
    """Print a warning message."""
    print(f"⚠️  {text}")


def print_error(text):
    """Print an error message."""
    print(f"❌ {text}")


def generate_secure_password(length=32):
    """Generate a secure random password."""
    return base64.b64encode(secrets.token_bytes(length)).decode('utf-8')[:length]


def generate_api_key(length=64):
    """Generate a secure API key."""
    return secrets.token_hex(length // 2)


def prompt_with_default(prompt_text, default="", password=False):
    """Prompt user for input with a default value."""
    if default:
        display_default = "***" if password and default else default
        prompt = f"{prompt_text} [{display_default}]: "
    else:
        prompt = f"{prompt_text}: "
    
    if password:
        value = getpass.getpass(prompt)
    else:
        value = input(prompt)
    
    return value.strip() if value.strip() else default


def prompt_yes_no(prompt_text, default=True):
    """Prompt user for yes/no confirmation."""
    default_text = "Y/n" if default else "y/N"
    response = input(f"{prompt_text} [{default_text}]: ").strip().lower()
    
    if not response:
        return default
    return response in ('y', 'yes')


def validate_twitter_credential(value):
    """Basic validation for Twitter credentials."""
    if not value or len(value) < 10:
        return False
    return True


def backup_existing_env():
    """Create a backup of existing .env file."""
    env_path = Path('.env')
    if env_path.exists():
        backup_path = Path(f'.env.backup.{int(os.path.getmtime(env_path))}')
        env_path.rename(backup_path)
        print_success(f"Existing .env backed up to: {backup_path}")
        return True
    return False


def load_existing_env():
    """Load existing .env values into a dictionary."""
    env_path = Path('.env')
    env_vars = {}
    
    if env_path.exists():
        with open(env_path, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    env_vars[key.strip()] = value.strip()
    
    return env_vars


def write_env_file(env_vars):
    """Write environment variables to .env file."""
    env_path = Path('.env')
    
    with open(env_path, 'w') as f:
        from datetime import datetime
        f.write("# Overseer Bot UI - Environment Configuration\n")
        f.write("# Generated by setup_env.py\n")
        f.write(f"# Created: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write("#\n")
        f.write("# SECURITY WARNING:\n")
        f.write("# This file contains sensitive credentials.\n")
        f.write("# - Never commit this file to version control\n")
        f.write("# - Keep permissions restricted (chmod 600 .env)\n")
        f.write("# - For cloud deployments, use platform environment variables\n")
        f.write("\n")
        
        # Write variables in logical groups
        sections = [
            ("TWITTER API CREDENTIALS", [
                'CONSUMER_KEY', 'CONSUMER_SECRET', 'ACCESS_TOKEN', 
                'ACCESS_SECRET', 'BEARER_TOKEN'
            ]),
            ("ADMIN AUTHENTICATION", [
                'ADMIN_USERNAME', 'ADMIN_PASSWORD'
            ]),
            ("WEBHOOK CONFIGURATION", [
                'WEBHOOK_API_KEY'
            ]),
            ("SERVER CONFIGURATION", [
                'PORT'
            ]),
            ("WALLET CONFIGURATION (Optional)", [
                'ENABLE_WALLET_UI', 'SOLANA_PRIVATE_KEY', 'SOLANA_RPC_ENDPOINT',
                'ETH_PRIVATE_KEY', 'ETH_RPC_ENDPOINT', 'BSC_RPC_ENDPOINT'
            ]),
            ("EXTERNAL API INTEGRATION (Optional)", [
                'OVERSEER_BOT_AI_URL', 'OVERSEER_BOT_AI_API_KEY',
                'TOKEN_SCALPER_URL', 'TOKEN_SCALPER_API_KEY',
                'POLL_INTERVAL', 'REQUEST_TIMEOUT'
            ]),
            ("AI FEATURES (Optional)", [
                'HUGGING_FACE_TOKEN'
            ])
        ]
        
        for section_name, keys in sections:
            f.write(f"# {section_name}\n")
            for key in keys:
                # Only write non-empty values to keep .env clean
                if key in env_vars and env_vars[key]:
                    f.write(f"{key}={env_vars[key]}\n")
            f.write("\n")
    
    # Set restrictive permissions (Unix-like systems)
    try:
        os.chmod(env_path, 0o600)
        print_success("Set .env file permissions to 600 (owner read/write only)")
    except Exception as e:
        print_warning(f"Could not set file permissions: {e}")
        print_info("On Windows, use file properties to restrict access")


def setup_twitter_credentials(env_vars):
    """Setup Twitter API credentials."""
    print_header("Twitter API Credentials")
    print_info("Get these from: https://developer.twitter.com/")
    print_info("You need a Twitter Developer account with API access")
    print()
    
    credentials = [
        ('CONSUMER_KEY', 'Consumer Key (API Key)'),
        ('CONSUMER_SECRET', 'Consumer Secret (API Secret)'),
        ('ACCESS_TOKEN', 'Access Token'),
        ('ACCESS_SECRET', 'Access Token Secret'),
        ('BEARER_TOKEN', 'Bearer Token')
    ]
    
    all_valid = True
    for key, description in credentials:
        current = env_vars.get(key, '')
        value = prompt_with_default(f"{description}", current)
        
        if validate_twitter_credential(value):
            env_vars[key] = value
        else:
            print_warning(f"Invalid {description} (too short or empty)")
            all_valid = False
            env_vars[key] = value  # Store anyway, let user fix later
    
    if not all_valid:
        print_warning("Some Twitter credentials may be invalid. Please verify them.")
    
    return env_vars


def setup_admin_auth(env_vars):
    """Setup admin authentication."""
    print_header("Admin Authentication")
    print_info("These credentials protect your monitoring dashboard")
    print()
    
    # Username
    current_username = env_vars.get('ADMIN_USERNAME', 'admin')
    username = prompt_with_default("Admin username", current_username)
    env_vars['ADMIN_USERNAME'] = username
    
    # Password
    current_password = env_vars.get('ADMIN_PASSWORD', '')
    if current_password and current_password != 'vault77secure':
        print_info("A password is already set")
        if prompt_yes_no("Generate a new secure password?", default=False):
            password = generate_secure_password()
            print_success(f"Generated password: {password}")
            print_warning("SAVE THIS PASSWORD! You won't see it again in the file.")
            input("Press Enter after you've saved the password...")
            env_vars['ADMIN_PASSWORD'] = password
        else:
            env_vars['ADMIN_PASSWORD'] = current_password
    else:
        if prompt_yes_no("Generate a secure password?", default=True):
            password = generate_secure_password()
            print_success(f"Generated password: {password}")
            print_warning("SAVE THIS PASSWORD! You won't see it again in the file.")
            input("Press Enter after you've saved the password...")
            env_vars['ADMIN_PASSWORD'] = password
        else:
            password = prompt_with_default("Enter password", "", password=True)
            env_vars['ADMIN_PASSWORD'] = password
    
    return env_vars


def setup_webhook(env_vars):
    """Setup webhook API key."""
    print_header("Webhook Configuration (Optional)")
    print_info("Used for Token-scalper integration and external webhooks")
    print()
    
    if prompt_yes_no("Do you want to configure webhook authentication?", default=False):
        current_key = env_vars.get('WEBHOOK_API_KEY', '')
        if current_key:
            print_info("A webhook API key is already set")
            if not prompt_yes_no("Generate a new API key?", default=False):
                env_vars['WEBHOOK_API_KEY'] = current_key
                return env_vars
        
        if prompt_yes_no("Generate a secure API key?", default=True):
            api_key = generate_api_key()
            print_success(f"Generated API key: {api_key}")
            print_warning("SAVE THIS KEY! Use it in Token-scalper configuration.")
            input("Press Enter after you've saved the API key...")
            env_vars['WEBHOOK_API_KEY'] = api_key
        else:
            api_key = prompt_with_default("Enter webhook API key")
            if api_key:
                env_vars['WEBHOOK_API_KEY'] = api_key
            else:
                # Remove key if user doesn't want to set it
                env_vars.pop('WEBHOOK_API_KEY', None)
    else:
        # Remove key if not configuring
        env_vars.pop('WEBHOOK_API_KEY', None)
    
    return env_vars


def setup_server(env_vars):
    """Setup server configuration."""
    print_header("Server Configuration")
    print()
    
    current_port = env_vars.get('PORT', '5000')
    port = prompt_with_default("Web server port", current_port)
    env_vars['PORT'] = port
    
    return env_vars


def setup_wallet(env_vars):
    """Setup wallet configuration."""
    print_header("Wallet Configuration (Optional)")
    print_info("Enable wallet features for Solana, Ethereum, and BSC")
    print_warning("Private keys are sensitive! Only add if you need wallet features.")
    print()
    
    if prompt_yes_no("Enable wallet features?", default=False):
        env_vars['ENABLE_WALLET_UI'] = 'true'
        
        # Solana
        print()
        print_info("Solana Configuration")
        if prompt_yes_no("Configure Solana wallet?", default=False):
            current_key = env_vars.get('SOLANA_PRIVATE_KEY', '')
            key = prompt_with_default("Solana private key (base58)", current_key, password=True)
            env_vars['SOLANA_PRIVATE_KEY'] = key
            
            current_rpc = env_vars.get('SOLANA_RPC_ENDPOINT', 'https://api.mainnet-beta.solana.com')
            rpc = prompt_with_default("Solana RPC endpoint", current_rpc)
            env_vars['SOLANA_RPC_ENDPOINT'] = rpc
        
        # Ethereum/BSC
        print()
        print_info("Ethereum/BSC Configuration")
        if prompt_yes_no("Configure Ethereum/BSC wallet?", default=False):
            current_key = env_vars.get('ETH_PRIVATE_KEY', '')
            key = prompt_with_default("ETH/BSC private key (hex, no 0x)", current_key, password=True)
            env_vars['ETH_PRIVATE_KEY'] = key
            
            current_eth_rpc = env_vars.get('ETH_RPC_ENDPOINT', 'https://eth.public-rpc.com')
            eth_rpc = prompt_with_default("Ethereum RPC endpoint", current_eth_rpc)
            env_vars['ETH_RPC_ENDPOINT'] = eth_rpc
            
            current_bsc_rpc = env_vars.get('BSC_RPC_ENDPOINT', 'https://bsc-dataseed1.binance.org')
            bsc_rpc = prompt_with_default("BSC RPC endpoint", current_bsc_rpc)
            env_vars['BSC_RPC_ENDPOINT'] = bsc_rpc
    else:
        env_vars['ENABLE_WALLET_UI'] = 'false'
    
    return env_vars


def setup_external_apis(env_vars):
    """Setup external API integration."""
    print_header("External API Integration (Optional)")
    print_info("Connect to overseer-bot-ai and Token-scalper APIs")
    print()
    
    if prompt_yes_no("Configure external API integration?", default=False):
        # Overseer Bot AI
        print()
        print_info("Overseer Bot AI Configuration")
        current_url = env_vars.get('OVERSEER_BOT_AI_URL', '')
        url = prompt_with_default("Overseer Bot AI URL", current_url)
        env_vars['OVERSEER_BOT_AI_URL'] = url
        
        if url:
            current_key = env_vars.get('OVERSEER_BOT_AI_API_KEY', '')
            api_key = prompt_with_default("Overseer Bot AI API Key (optional)", current_key, password=True)
            env_vars['OVERSEER_BOT_AI_API_KEY'] = api_key
        
        # Token Scalper
        print()
        print_info("Token-scalper Configuration")
        current_url = env_vars.get('TOKEN_SCALPER_URL', '')
        url = prompt_with_default("Token-scalper URL", current_url)
        env_vars['TOKEN_SCALPER_URL'] = url
        
        if url:
            current_key = env_vars.get('TOKEN_SCALPER_API_KEY', '')
            api_key = prompt_with_default("Token-scalper API Key (optional)", current_key, password=True)
            env_vars['TOKEN_SCALPER_API_KEY'] = api_key
        
        # Polling settings
        print()
        current_interval = env_vars.get('POLL_INTERVAL', '15')
        interval = prompt_with_default("Polling interval (seconds)", current_interval)
        env_vars['POLL_INTERVAL'] = interval
        
        current_timeout = env_vars.get('REQUEST_TIMEOUT', '5')
        timeout = prompt_with_default("Request timeout (seconds)", current_timeout)
        env_vars['REQUEST_TIMEOUT'] = timeout
    
    return env_vars


def setup_optional_features(env_vars):
    """Setup optional features."""
    print_header("Optional Features")
    print()
    
    # Hugging Face
    if prompt_yes_no("Configure Hugging Face AI (for enhanced responses)?", default=False):
        current_token = env_vars.get('HUGGING_FACE_TOKEN', '')
        token = prompt_with_default("Hugging Face API token", current_token, password=True)
        env_vars['HUGGING_FACE_TOKEN'] = token
    
    return env_vars


def main():
    """Main setup function."""
    print_header("🤖 Overseer Bot UI - Environment Setup")
    print()
    print("This script will help you create or update your .env configuration file.")
    print("You can skip optional sections by answering 'no' to prompts.")
    print()
    print_warning("IMPORTANT: Your .env file contains sensitive credentials.")
    print_warning("Never commit it to version control or share it publicly.")
    print()
    
    # Check if .env.example exists
    if not Path('.env.example').exists():
        print_error("Error: .env.example not found!")
        print_info("Make sure you're running this script from the repository root.")
        sys.exit(1)
    
    # Check for existing .env
    env_path = Path('.env')
    if env_path.exists():
        print_info("Existing .env file found")
        if not prompt_yes_no("Do you want to update it?", default=True):
            print_info("Setup cancelled")
            sys.exit(0)
        
        if prompt_yes_no("Create a backup first?", default=True):
            backup_existing_env()
    
    # Load existing values
    env_vars = load_existing_env()
    
    # Guide user through setup
    try:
        env_vars = setup_twitter_credentials(env_vars)
        env_vars = setup_admin_auth(env_vars)
        env_vars = setup_webhook(env_vars)
        env_vars = setup_server(env_vars)
        
        # Optional configurations
        env_vars = setup_wallet(env_vars)
        env_vars = setup_external_apis(env_vars)
        env_vars = setup_optional_features(env_vars)
        
        # Write the file
        print_header("Writing Configuration")
        write_env_file(env_vars)
        print_success("Configuration saved to .env")
        
        # Final instructions
        print_header("✅ Setup Complete!")
        print()
        print("Next steps:")
        print("1. Review your .env file: cat .env (Unix) or type .env (Windows)")
        print("2. Install dependencies: pip install -r requirements.txt")
        print("3. Run the bot: python overseer_bot.py")
        print("4. Access dashboard: http://localhost:5000")
        print()
        print_warning("Remember to keep your .env file secure!")
        print_info("For cloud deployment, set these as environment variables in your platform")
        
    except KeyboardInterrupt:
        print()
        print_warning("Setup interrupted by user")
        sys.exit(1)
    except Exception as e:
        print_error(f"Setup failed: {e}")
        sys.exit(1)


if __name__ == '__main__':
    if len(sys.argv) > 1 and sys.argv[1] in ('--help', '-h'):
        print(__doc__)
        sys.exit(0)
    
    main()
